services:
  caddy:
    image: caddy:latest
    container_name: caddy-https
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./html:/srv:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - app
  app:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./html:/usr/share/nginx/html:ro

volumes:
  caddy-data:
  caddy-config:
