services:
  reverse-proxy:
    build: .
    container_name: reverse-proxy
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/certs
      - ~/.local/share/mkcert:/mkcert:ro
    depends_on:
      - web-server
  web-server:
    image: nginx:alpine
    container_name: web-server
    volumes:
      - ./html:/usr/share/nginx/html:ro
