services:
  minica:
    build: .
    container_name: minica
    environment:
      - DOMAINS=localhost,127.0.0.1,::1
    volumes:
      - ./certs:/etc/nginx/certs

  app:
    image: nginx:alpine
    container_name: nginx-app
    depends_on:
      - minica
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs