services:
  web-server:
    build: .
    container_name: web-server
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs
      - ~/.local/share/mkcert:/mkcert:ro
