services:
  reverse-proxy:
    build: ./nginx
    container_name: reverse-proxy
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - web-server
    networks:
      - internal

  web-server:
    build: ./apache
    container_name: web-server
    expose:
      - "8080"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./html:/usr/local/apache2/htdocs:ro
    networks:
      - internal

networks:
  internal:
    driver: bridge