services:
  web-server:
    build: .
    container_name: web-server
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/certs
      - ./html:/srv:ro
      - ~/.local/share/mkcert:/mkcert:ro
