services:
  traefik:
    image: traefik:v3
    container_name: traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
  app:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./html:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.http.routers.app-https.rule=Host(`localhost`)"
      - "traefik.http.routers.app-https.entrypoints=websecure"
      - "traefik.http.routers.app-https.service=app"
      - "traefik.http.routers.app-https.tls=true"
      - "traefik.http.routers.app-http.rule=Host(`localhost`)"
      - "traefik.http.routers.app-http.entrypoints=web"
      - "traefik.http.routers.app-http.service=app"
